const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLCETIONS_FAILURE: 'FETCH_COLLCETIONS_FAILURE',
};

export default ShopActionTypes;
